Repository oss-slu/lrda_mobile, pull requests merged in 2023-10, with the labels that each got.

#76 (WIP for issue 75) Fixing Top Speaker Bug for Recording
  .github/workflows/Native.yml
  .idea/.gitignore
  .idea/lrda_mobile.iml
  .idea/modules.xml
  .idea/vcs.xml
  __tests__/AddNoteScreen.test.tsx
  assets/animations/animation_llwlq2y0.json
  assets/animations/companion.json
  lib/components/audio.tsx
  package.json
  setupTests.js
  yarn.lock
Labels: bug

#80 WIP for issue 77 Audio for Android and iOS
  __tests__/AudioRecorder.test.tsx
  lib/components/audio.tsx
  lib/utils/S3_proxy.ts
  package.json
  yarn.lock
Labels: bug

#79 WIP on Issue 78
  lib/screens/EditNoteScreen.tsx
Labels: bug

#90 (WIP 86)ClockRedjusting
  lib/components/time.tsx
Labels: bug, documentation

#89 removed top image
  lib/screens/AddNoteScreen.tsx
  lib/screens/EditNoteScreen.tsx
  lib/screens/mapPage/ExploreScreen.js
  package.json
  yarn.lock
Labels: enhancement

#88 (WIP #87) Implementing Switch for Dark Mode
  App.tsx
  __tests__/AddNoteScreen.test.tsx
  __tests__/InsertImageNoteScreen.test.tsx
  lib/components/ThemeProvider.js
  lib/components/colors.tsx
  lib/navigation/AppNavigator.tsx
  lib/screens/AddNoteScreen.tsx
  lib/screens/EditNoteScreen.tsx
  lib/screens/HomeScreen.tsx
  lib/screens/MorePage.tsx
  lib/screens/ProfilePage.tsx
  lib/screens/SettingsScreen.tsx
  lib/screens/mapPage/ExploreScreen.js
  lib/utils/async_storage.js
  styles/pages/HomeStyles.ts
  styles/pages/NoteStyles.ts
  styles/pages/NoteStyles.tsx
Labels: enhancement, good first issue
